### ISSUE TITLE
Intel MPI MPI_ISSEND invalid tag when writing large vtu files

### ISSUE THREAD

**Issue by wanyingw** [geodynamics/aspect#4037] opened 2021-05-15 03:28 UTC
I installed ASPECT on Frontera and was hoping to run 3d spherical models with global refinement >=6. I got errors from the MPI_ISSEND suggesting invalid tag. Please see below for the complete error message. 
I checked the MPI tag with a script (from https://community.intel.com/t5/Intel-oneAPI-HPC-Toolkit/Bug-Report-MPI-IRECV-invalid-tag-problem/td-p/1014681), and MPI_TAG_UB is set to be 1681915906, but the internal UB is set to be 1048574. Any tag larger than 1048574 would cause the error.
Since the error occurs during the postprocessing stage, @gassmoeller suggested that I try writing the output into multiple files by setting "Number of grouped files" to a larger number, and this resolved the issue. 

The log file and error message: 
Number of active cells: 25,165,824 (on 7 levels)
Number of degrees of freedom: 833,816,842 (606,340,614+25,362,690+202,113,538)

*** Timestep 0:  t=0 years, dt=0 years
   Solving temperature system... 0 iterations.
   Solving Stokes system... 17+0 iterations.

   Postprocessing:
Abort(67743492) on node 1318 (rank 1318 in comm 0): Fatal error in PMPI_Issend: Invalid tag, error stack:
PMPI_Issend(156): MPI_Issend(buf=0x24706b60, count=271332, MPI_BYTE, dest=0, tag=1050618, comm=0x84000004, request=0x7f20001da380) failed
PMPI_Issend(95).: Invalid tag, value is 1050618
Abort(873049860) on node 1345 (rank 1345 in comm 0): Fatal error in PMPI_Issend: Invalid tag, error stack:
PMPI_Issend(156): MPI_Issend(buf=0x22c42080, count=525027, MPI_BYTE, dest=0, tag=1072045, comm=0x84000004, request=0x7f200004e180) failed
PMPI_Issend(95).: Invalid tag, value is 1072045
Abort(134852356) on node 1316 (rank 1316 in comm 0): Fatal error in PMPI_Issend: Invalid tag, error stack:
PMPI_Issend(156): MPI_Issend(buf=0x239f02b0, count=146182, MPI_BYTE, dest=0, tag=1049016, comm=0x84000004, request=0x7f20001e1640) failed
PMPI_Issend(95).: Invalid tag, value is 1049016
Abort(671723268) on node 1317 (rank 1317 in comm 0): Fatal error in PMPI_Issend: Invalid tag, error stack:
PMPI_Issend(156): MPI_Issend(buf=0x22beb1b0, count=185563, MPI_BYTE, dest=0, tag=1049817, comm=0x84000004, request=0x7f20000c9600) failed
PMPI_Issend(95).: Invalid tag, value is 1049817
Abort(537505540) on node 1319 (rank 1319 in comm 0): Fatal error in PMPI_Issend: Invalid tag, error stack:
PMPI_Issend(156): MPI_Issend(buf=0x24134f50, count=391469, MPI_BYTE, dest=0, tag=1051419, comm=0x84000004, request=0x7f20001b2c40) failed
PMPI_Issend(95).: Invalid tag, value is 1051419
Abort(873049860) on node 1320 (rank 1320 in comm 0): Fatal error in PMPI_Issend: Invalid tag, error stack:
PMPI_Issend(156): MPI_Issend(buf=0x2476a5b0, count=468146, MPI_BYTE, dest=0, tag=1052220, comm=0x84000004, request=0x7f200005c300) failed
PMPI_Issend(95).: Invalid tag, value is 1052220
TACC:  MPI job exited with code: 4

**Comment by tjhei** [comment] 2021-05-16 00:22
Which filesystem are you using for the graphical output? Is this vtu or hdf5 output?

**Comment by wanyingw** [comment] 2021-05-16 00:47
I'm using vtu.

**Comment by tjhei** [comment] 2021-05-16 03:16
What value for grouping works and what value fails? Do you know how big the sum of all files for the timestep in MB is?

**Comment by gassmoeller** [comment] 2021-05-17 14:06
grouping in 1 file fails, grouping in 16 files works (as far as I know). I dont know the file size, but the model has 800 million dofs. @wanyingw can you clarify how large the files are?

**Comment by wanyingw** [comment] 2021-05-17 17:21
The total size of the vtu outputs is ~15 to 18G, and right now I split the output to 30 files. I haven't try other output file numbers yet.

**Comment by tjhei** [comment] 2021-05-25 19:31
Thank you for the information. My current best guess is that MPI IO fails for large (>4GB ?) files. I will try to reproduce.

**Comment by tjhei** [comment] 2021-05-27 22:41
I can confirm that this problem does not occur on a different machine with GCC+openmpi.

**Comment by wanyingw** [comment] 2021-05-28 19:54
So looks like it's a problem with my compilation, it's weird since I compiled it the same way as Rene did in the Frontera instruction, and Rene's models don't have the same problem.

**Comment by tjhei** [comment] 2021-05-28 20:47
Thanks foe letting me know. I have been digging around and tried to reproduce...

**Comment by tjhei** [comment] 2021-05-28 20:50
@zjiaqi2018 It looks like there is nothing for you to do here.

**Comment by gassmoeller** [comment] 2021-06-02 15:09
> So looks like it's a problem with my compilation, it's weird since I compiled it the same way as Rene did in the Frontera instruction, and Rene's models don't have the same problem.

I never tried writing a single file larger than 4 GB on Frontera. So at the moment I would think this is a problem with Frontera's MPI-IO (impi/19.0.9) or the file system (Lustre). I do not think writing a single file of that size would be very useful anyway, because visualization will likely take forever. I am not sure how we could prevent this though.

**Comment by tjhei** [comment] 2021-06-02 15:30
Okay, that could be. @zjiaqi2018 tried it out on our local cluster with intel + intel MPI (right, Jiaqi?) and there was no issue in writing 10+ GB output files.

**Comment by zjiaqi2018** [comment] 2021-06-02 15:37
> Okay, that could be. @zjiaqi2018 tried it out on our local cluster with intel + intel MPI (right, Jiaqi?) and there was no issue in writing 10+ GB output files.

Correct, intel/19.1  +  intelmpi/21.1.1 outputs a single file larger than 16GB without any issue.

**Comment by gassmoeller** [comment] 2021-06-02 16:32
Do you have a simple example file for that? I could easily try running that on Frontera.

**Comment by wanyingw** [comment] 2021-06-02 16:38
Yes, I'll send you a simple case.

**Comment by tjhei** [comment] 2021-11-11 22:24
@gassmoeller @wanyingw do you have any success with reproducing this bug? I am seeing the same error on Frontera when doing large IO with intel/19.1.1.

**Comment by wanyingw** [comment] 2021-11-12 17:08
I still have the same issue when postprocessing large models with one vtu.
But as Rene suggested dividing the output into several segments works well
for me.

**Comment by tjhei** [comment] 2021-11-16 22:01
I made some progress here. The workaround is the following:
```
export MPIR_CVAR_CH4_OFI_RANK_BITS=17
export MPIR_CVAR_CH4_OFI_TAG_BITS=22
```
with that, I can write very large vtu files with my small test application. I did not test ASPECT, though. Maybe you can try?

Background:
Intel placed limitation on the maximum number of tags starting with Intel MPI 19 and their MPI IO implementation uses too many tags by default when the file size becomes large. Intel uses this for faster tag matching to improve performance (and so rank+tag+something need to fit into 64 bits). One can tune the values with the env variables above. I am in conversation with TACC for a better fix but this is all we have for now.

**Comment by bangerth** [comment] 2021-11-17 22:33
Ah, what an unfortunate choice and unintended consequence :-(

**Comment by tjhei** [comment] 2022-02-14 17:50
I am closing this, as there is not much else we can do.

**Closed by tjhei** 2022-02-14 17:50 UTC
