### ISSUE TITLE
Entropy stabilization when shearing

### ISSUE THREAD

**Issue by jdannberg** [geodynamics/aspect#967] opened 2016-06-26 04:35 UTC
We apply standard entropy viscosity to a shear bands test and see oscillations where the velocity is small. This is because the stabilization is scaled with the maximum velocity in a cell, and does not see shearing. 
@tjhei suggests to use `max(max_velocity, strain_rate*h)`.

**Comment by bangerth** [comment] 2016-06-26 05:02
This is a duplicate of #293.

**Closed by bangerth** 2016-06-26 05:02 UTC

**Comment by tjhei** [comment] 2016-06-26 05:36
Not quite, because we have a nonzero but small velocity in every cell.

**Comment by bangerth** [comment] 2016-06-26 05:41
But aren't these both symptoms of the same underlying cause?
