### ISSUE TITLE
parsing parameters for phase entry, should we allow empty entry in Utilities::parse_map_to_double_array

### ISSUE THREAD

**Issue by lhy11009** [geodynamics/aspect#3290] opened 2019-11-11 23:27 UTC
@gassmoeller 
I see that by calling the function 
Utilities::parse_map_to_double_array we by default allow empty entry. 

However, there can be an issue if the entry is empty, say, I don't enter any parameters for diffusion creep, there will be a problem when calling the phase_average function. Because, then, there will only be one value for some vector, say, prefactors_diffusion only has value of 1e-15 in my run(I output it when debugging),  but the phase_averge function need this vector to have composition + phase value

How do we fix this? One way is we don't allow empty entry. Otherwise, we fix the vector to have composition + phase default values when entry is empty. Or there are other ways that makes more sense?

**Comment by gassmoeller** [comment] 2019-11-12 15:58
We currently allow empty entries for the phase function parameters, because there might be no phase transition. We do not allow empty entries for things like the equation of state (there is always background material). The same should be done for the viscosity parameters. As far as I can see the default is to not allow empty entries unless you specifically hand over a parameter to the parse_map_to_double_array function. Which branch do you use, and can you link to a file where the default is true?

**Comment by gassmoeller** [comment] 2019-12-09 19:54
@lhy11009 Since I could not reproduce your issue I am closing it for now. If you have an example that shows the problem feel free to reopen.

**Closed by gassmoeller** 2019-12-09 19:54 UTC
