### ISSUE TITLE
track the location of the rising stokes sphere

### ISSUE THREAD

**Issue by liaokp** [geodynamics/aspect#2243] opened 2018-05-14 22:25 UTC
In my 2D simple model (a box), I have a buoyant rising stokes sphere, I want to track its location (Y-coordinate) at every time step and output it to a file. The way I tried is to put in a single passive particle at the center of the sphere (see model file line 176 - 187, complete model file and plugin is attached), but ASPECT failed to run my model. 

168 subsection Postprocess
169   set List of postprocessors = visualization,topography,velocity statistics,depth average,particles
170   subsection Visualization
171     set Time between graphical output = 1e5
172     set List of output variables = density, viscosity, shear stress, nonadiabatic pressure
173     # set Output format = gnuplot
174   end
175
176   subsection Particles
177     set Number of particles = 1
178     set Time between data output = 0.0
179     set Data output format = ascii
180     set List of particle properties = function, initial composition, initial position
181     set Particle generator name = ascii file
182
183     subsection Function
184       set Variable names      = x,y
185       set Function expression = if( sqrt( (x-1000.e3)^2 + (y-60.e3)^2 ) > 1.e3, 0, 1)
186     end
187   end
188 end

## 
error message is really long, repeat of following lines:

An error occurred in line <3520> of file </home1/04308/liaokp/progs/dealii-8.5.0/include/deal.II/dofs/dof_accessor.templates.h> in function
    void dealii::DoFCellAccessor<DoFHandlerType, lda>::get_dof_values(const InputVector&, ForwardIterator, ForwardIterator) const [with InputVector = dealii::TrilinosWrappers::MPI::Vector; ForwardIterator = double*; DoFHandlerType = dealii::DoFHandler<2>; bool level_dof_access = false]
The violated condition was: 
    this->is_artificial() == false
Additional information: 
    Can't ask for DoF indices on artificial cells.

Stacktrace:

#0  /home1/04308/liaokp/progs/deal.II-8.5/lib/libdeal_II.g.so.8.5.0: dealii::MappingQ1Eulerian<2, dealii::TrilinosWrappers::MPI::Vector, 2>::get_vertices(dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&) const
#8  /work/04308/liaokp/lonestar/aspect/aspect: boost::signals2::detail::signal_impl<void (aspect::SimulatorAccess<2> const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (aspect::SimulatorAccess<2> const&)>, boost::function<void (boost::signals2::connection const&, aspect::SimulatorAccess<2> const&)>, boost::signals2::mutex>::operator()(aspect::SimulatorAccess<2> const&)
#9  /work/04308/liaokp/lonestar/aspect/aspect: aspect::Simulator<2>::run()
#10  /work/04308/liaokp/lonestar/aspect/aspect: main

SIGABRT received
#1  /home1/04308/liaokp/progs/deal.II-8.5/lib/libdeal_II.g.so.8.5.0: dealii::MappingQGeneric<2, 2>::transform_real_to_unit_cell(dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&, dealii::Point<2, double> const&) const
#2  /home1/04308/liaokp/progs/deal.II-8.5/lib/libdeal_II.g.so.8.5.0: std::pair<dealii::parallel::distributed::Triangulation<2, 2>::active_cell_iterator, dealii::Point<2, double> > dealii::GridTools::find_active_cell_around_point<2, dealii::parallel::distributed::Triangulation, 2>(dealii::Mapping<2, 2> const&, dealii::parallel::distributed::Triangulation<2, 2> const&, dealii::Point<2, double> const&)
#3  /work/04308/liaokp/lonestar/aspect/aspect: aspect::Particle::Generator::Interface<2>::generate_particle(dealii::Point<2, double> const&, unsigned int) const
#8  /work/04308/liaokp/lonestar/aspect/aspect: boost::signals2::detail::signal_impl<void (aspect::SimulatorAccess<2> const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (aspect::SimulatorAccess<2> const&)>, boost::function<void (boost::signals2::connection const&, aspect::SimulatorAccess<2> const&)>, boost::signals2::mutex>::operator()(aspect::SimulatorAccess<2> const&)
#9  /work/04308/liaokp/lonestar/aspect/aspect: aspect::Simulator<2>::run()
#10  /work/04308/liaokp/lonestar/aspect/aspect: main

## 
Rene suggested to do:
Replace line 72 of aspect's source/particle/generator/interface.cc, which should read:
        catch (GridTools::ExcPointNotFound<dim> &)
by
        catch (...)

I tried this, re-complied ASPECT, run my model, the problem remains, same error message as above.

##
Please advise me a way to realize my goal: tracking the location of the moving sphere
Thank you very much!
[simpler-with-crust.zip](https://github.com/geodynamics/aspect/files/2002780/simpler-with-crust.zip)

**Comment by gassmoeller** [comment] 2018-05-16 19:32
Kunpeng,
I was trying to reproduce your problem, but I am having trouble finding the combination of deal.II and ASPECT that creates the problem. Please attach the output/log.txt file of your run. Also please post the commit hash of your ASPECT version (go to your ASPECT source directory and type `git log` and post the uppermost commit).

**Comment by tjhei** [comment] 2018-05-17 20:04
> Rene suggested to do:

This won't work because ``Assert(...)`` won't be thrown but causes an abort.

This looks to me like a bug inside deal.II: we are missing a check to only look at non-artificial cells before looking at the cells in ``adjacent_cells``. This bugs seems to be in 8.5 and 9.0. ;-(

While this can be fixed in deal.II, I am not sure how to fix ASPECT here. Rene, any idea?

Kunpeng, how many MPI procs are you using?

**Comment by liaokp** [comment] 2018-05-18 16:35
Hi Rene and Timo,

1. output/log.txt file is empty, only:
```
-- This is ASPECT, the Advanced Solver for Problems in Earth's ConvecTion.
--     . version 2.0.0-pre
--     . running in DEBUG mode
--     . running with 528 MPI processes
--     . using Trilinos

```

2. commit hash of my ASPECT version is:
```
commit 6817984e8dc675393863804db3c7a74070fe852d
Merge: d3c2c47 a428eb3
Author: Timo Heister <timo.heister@gmail.com>
Date:   Sat Jun 10 13:33:37 2017 +0200

    Merge pull request #1811 from bangerth/doc-update
    
    Update the manual section on tests.
```

3. I used multi processors on Lonestar5. I tried 96 and 528, both didn't work.

Kunpeng

**Comment by tjhei** [comment] 2018-05-18 16:44
> Should GridTools::get_active_vertices not return artificial vertices? Or should MappingQEulerian assume undeformed vertices for non local cells?

I don't think it make sense to ignore the mapping and return undeformed cells because they could be far away. I think ignoring artificial cells makes the most sense.

**Comment by gassmoeller** [comment] 2018-05-18 17:10
I am just afraid that this might change results for other mappings (i.e. could users rely on the fact that `get_active_vertices` also returns vertices on artifical cells? Is that supported?)

**Comment by gassmoeller** [comment] 2018-05-18 17:21
It also seems that this bug was actually reported in #2050 in a different context, but we never got around to fixing it. I will think about a workaround (probably a fix for deal.II, and a reimplementation of the function in aspect/compat.h).

**Comment by gassmoeller** [comment] 2018-05-18 21:44
A first proposal for a solution is in #6630, but it might take a while until that is figured out, and we have a working fix in aspect. @liaokp: I will email you a suggestion for how to work around this for the moment for your particular model.

**Comment by gassmoeller** [comment] 2019-05-08 18:28
This was fixed a while ago.

**Closed by gassmoeller** 2019-05-08 18:28 UTC
Labels: bug
