### ISSUE TITLE
Expected template-name before "<" token...

### ISSUE THREAD

**Issue by XieJChris** [geodynamics/aspect#3494] opened 2020-05-04 14:08 UTC
I want to write another new .cc code like /aspect/cookbooks/inner_core_convection/inner_core_convection.cc, and I took the same syntax like template<int dim> class EnergyChange:public Interface<dim>{} used in the code mentioned above, but after compiling, problems arises, it keeps telling me the error that 'expected template-name before"<"token class EnergyChange:public Interface<dim>, and the left < was marked red, so, what's wrong?

**Comment by tjhei** [comment] 2020-05-04 15:28
Does the original ``inner_core_convection.cc`` compile for you? If yes, then what you are doing in your  code is the problem. Without seeing what you do, it is hard to know what is going wrong.

**Comment by tjhei** [comment] 2020-07-24 18:22
I assume that I was able to help you. If not, please open a thread on the ASPECT forums. Closing this issue, as this is not a bug as far as I can tell.

**Closed by tjhei** 2020-07-24 18:22 UTC
