### ISSUE TITLE
A “SIGFPE received” error when running "crustal_model_2D"

### ISSUE THREAD

**Issue by wkillers** [geodynamics/aspect#1851] opened 2017-07-12 05:10 UTC
Hi,

When I run the "crustal_model_2D" in cookbooks with mpi, the running terminated at timestep=1 and I got some returned message said "SIGFPE received", this also happened for "crustal_model_3D". Whereas, other examples like "convection-box" "platelike-boundary" "composition-active" run well, What's the problem is?

BTW: I also found a strange thing when using MPI, e.g., when I was trying to use 24 cores to run the model (for example the "platelike-boundary.prm"), I only got 16 xx.vtu files in solution directory, but the results seems correct when view in Visit as shown in the manual. Why does this happen?

Thanks.

**Comment by gassmoeller** [comment] 2017-07-12 17:09
Thanks for raising these issues. Could you provide us with the exact number of cores, version of ASPECT and a copy of the error message for the SIGFPE problem? This might be a problem with your installation or a problem with the cookbook, but we need this information to reproduce the issue.

For the second hint: This is our default behavior. ASPECT used to write one file per process, but when you have hundreds or thousands of processes writing in parallel this quickly overwhelms the I/O system of clusters. If you on the other hand write a single file this file might become too large to be visualized. So we decided on a default of 16 files per timestep (if you use more than 16 cores). You can modify this with the input parameter `Postprocess/Visualization/Number of grouped files`.

**Comment by wkillers** [comment] 2017-07-13 01:24
Hi, 
Thanks for the reply. 

The number of cores that I used for "crustal_model_2D" is 24, the version of ASPECT is the master branch that I download from github(not use git clone because I run model on a cluster that can not connect to outside network). The error message for the SIGFPE problem is like this:
```
SIGFPE received
Connection closed by 10.11.100.1
```
There is nothing else in the error report message. And the log file in output is attatched.
[log.txt](https://github.com/geodynamics/aspect/files/1143766/log.txt)
I think it is more likely that this is the problem of the cookbook rather than my installation, because other cookbooks seems run without this problem, only these crustal_model_2(3)D got this problem.

Thanks.

**Comment by tjhei** [comment] 2017-07-13 14:36
It runs correctly for me with 24 cores (even though it needs a very high number of nonlinear iterations, @naliboff is that expected?).

@wkillers can you please post your detailed.log from your ASPECT build directory?

**Comment by gassmoeller** [comment] 2017-07-13 17:36
I can reproduce the issue, and it even happens on a single core for me. A run with `gdb --args aspect crustal_model_2d.prm` locates the problem in line 94 of `source/material_model/drucker_prager.cc`, namely in this line

```
const double strain_rate_effective_inv = 1/(2*std::sqrt(strain_rate_effective));
```

Going back to where `strain_rate_effective` is computed it seems that in this model the individual components of the strain rate tensor at quadrature point 0 (i.e. `in.strain_rate[0]`) are zero. 
In line 115 we catch this case by prescribing a maximum viscosity (so it does not lead to wrong results), but we should probably catch the case before dividing by zero in line 94.
I would suggest moving the if-statement from line 115 to line 90 and putting all lines in between into the else-statement. 

@wkillers are you interested in making your first contribution, or would you prefer somebody else to make the change? We can give advice on the process.

**Comment by naliboff** [comment] 2017-07-13 20:05
@tjhei - yes, I think that number of non-linear iterations is not surprising. The non-linear solver tolerance in the literature typically used for this type of problem ranges anywhere from 1e-3 to 1e-5 (noting that of course the actual values depend on the tolerance is defined). At some point with Picard iterations and Drucker Prager plasticity the problem usually reaches a tolerance around 1e-4 - 1e-6 where it does not converge further. 

@MFraters - does the Newton solver improve on this limit or do you simply reach the solution faster in most cases?

@gassmoeller - Sounds reasonable :+1:  

@wkillers - Good catch and please do let us know if you would like to make the change and help us walk you through the process.

**Comment by wkillers** [comment] 2017-07-14 07:16
@gassmoeller @naliboff 
Thanks for the reply and advise. Since I am quite new to C++ or deal.II, and I hardly can spend too much time on this problem recently, I would be very appreciate if anyone else can make the change. Very sorry about that.

Thank you.

**Comment by MFraters** [comment] 2017-07-14 13:40
@naliboff The Newton solver will usually allow you to tolerances way below what the Picard iterations allows you to do (I have even been able to sometimes reach 1e-19). The Drucker prager case (with an angle of internal friction of 30) is a notoriously difficult case though (see the Spiegelman 2016 paper, doi:10.1002/2015GC006228). 

I just tested it and for the first timestep it is possible with the newton solver to get to a tolerance of about 1e-16. But things seems to be more difficult after the first timestep.

**Comment by naliboff** [comment] 2017-07-15 00:12
@MFraters  1e-19, wow!  Yes, the friction angles near 30 and above are an absolute nightmare. It would be interesting to see how the velocity field looks on each non-linear iteration after the first time step for the Spiegelman setup. Something to discuss after your paper comes out :+1:

**Comment by gassmoeller** [comment] 2017-08-16 00:22
@wkillers: Could you check if your problem was resolved in the newest development version? If so, please feel free to close this issue.

**Comment by naliboff** [comment] 2017-08-17 21:46
One data point: I am able to run `crustal_model_2D` without issue using the latest development version.

**Comment by gassmoeller** [comment] 2017-08-29 12:57
Since this issue seems resolved, I will close it for now. If the problem reappears, feel free to reopen.

**Closed by gassmoeller** 2017-08-29 12:57 UTC
Labels: bug, starter project
