### ISSUE TITLE
GMG solver crashes in models with Material averaging = project to Q1 only viscosity and strong viscosity contrasts

### ISSUE THREAD

**Issue by jdannberg** [geodynamics/aspect#4466] opened 2022-01-27 22:44 UTC
I have been trying to set up models with the GMG and the option `set Material averaging = project to Q1 only viscosity`. In many of my Earth-like application cases (with moderately strong viscosity contrasts), I get the following error message:

```
--------------------------------------------------------
An error occurred in line <1207> of file </home/juliane/software/aspect-6/source/simulator/stokes_matrix_free.cc> in function
    void aspect::MatrixFreeStokesOperators::ABlockOperator<dim, degree_v, number>::set_diagonal(const dealii::LinearAlgebra::distributed::Vector<number>&) [with int dim = 2; int degree_v = 2; number = double]
The violated condition was: 
    local_element > 0.
Additional information: 
    No diagonal entry in a positive definite operator should be zero or
    negative.

Stacktrace:
-----------
#0  /home/juliane/software/aspect-6/build/aspect: aspect::MatrixFreeStokesOperators::ABlockOperator<2, 2, double>::set_diagonal(dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&)
#1  /home/juliane/software/aspect-6/build/aspect: aspect::StokesMatrixFreeHandlerImplementation<2, 2>::build_preconditioner()
#2  /home/juliane/software/aspect-6/build/aspect: aspect::Simulator<2>::assemble_and_solve_stokes(bool, double*)
#3  /home/juliane/software/aspect-6/build/aspect: aspect::Simulator<2>::solve_single_advection_single_stokes()
#4  /home/juliane/software/aspect-6/build/aspect: aspect::Simulator<2>::solve_timestep()
#5  /home/juliane/software/aspect-6/build/aspect: aspect::Simulator<2>::run()
#6  /home/juliane/software/aspect-6/build/aspect: void run_simulator<2>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool)
#7  /home/juliane/software/aspect-6/build/aspect: main
--------------------------------------------------------

```

This is on the current main branch, and with deal.II 9.3.0. I’ve checked in the debugger, and the `local_element` value that triggers the error is around -1e21 (so it’s on the order of magnitude of a viscosity, just negative). 

I have attached an example file that causes this problem (and the log file). If I switch the solver to AMG (with no other change), the solver works and produces the following viscosity:
![viscosity](https://user-images.githubusercontent.com/7517347/151453314-7e27849b-c87c-4882-bb17-915e8ee53f64.png)
Using the GMG and setting the Material averaging to harmonic average only viscosity works as well. 

[GMG_project_Q1.prm.txt](https://github.com/geodynamics/aspect/files/7954267/GMG_project_Q1.prm.txt)

[screen-output.txt](https://github.com/geodynamics/aspect/files/7954271/screen-output.txt)

**Comment by tjhei** [comment] 2022-01-28 16:38
Thank you, @jdannberg . This is compressible, right? Is there an easy way to make this incompressible to make sure that this doesn't cause the issue?

@zjiaqi2018 can you try to reproduce this, please? We are probably using this code to compute the diagonal:
https://github.com/geodynamics/aspect/blob/27e31dcd7ccd56a4d67e0cd622058f839a224f57/source/simulator/stokes_matrix_free.cc#L2720-L2722
Is that true in this situation? Can you try if the crash goes away if you use 0 velocity boundary instead of tangential in the .prm?

**Comment by jdannberg** [comment] 2022-01-28 18:03
Yes, it's compressible. I am attaching an incompressible version here (leaving the viscosity the same, but taking the rest of the material properties from the simple model). I still see the same behavior. 

If I change both boundaries to zero velocity, it works again (if I only change one, it's still crashing). 

[GMG_project_Q1_incompressible.prm.txt](https://github.com/geodynamics/aspect/files/7960840/GMG_project_Q1_incompressible.prm.txt)

**Comment by zjiaqi2018** [comment] 2022-01-29 05:13
> @zjiaqi2018 can you try to reproduce this, please? We are probably using this code to compute the diagonal:

Sure, I will.

**Comment by zjiaqi2018** [comment] 2022-01-31 20:11
I found that the viscosity here is negative at some quadrature points, but `min_el` is positive! @tjhei 
https://github.com/geodynamics/aspect/blob/27e31dcd7ccd56a4d67e0cd622058f839a224f57/source/simulator/stokes_matrix_free.cc#L1488

**Comment by tjhei** [comment] 2022-01-31 21:17
What is min_el and max_el here? Having values undershoot in the line you linked is not necessarily a problem, I think.
The min/max assignment a few lines below should fix the negative entries (hopefully).

**Comment by tjhei** [comment] 2022-02-02 13:50
Just a quick update: we think we have a fix for this that@zjiaqi2018 should be able to finish in a few days.

Part one is #4472

**Comment by tjhei** [comment] 2022-02-14 17:45
I am closing this because I think #4479 should have fixed this.

**Closed by tjhei** 2022-02-14 17:45 UTC

**Comment by jdannberg** [comment] 2022-02-15 01:25
Great, thank you! I will try this out with the new cookbook I made (which was the model where I originally noticed the problem).
