### ISSUE TITLE
Write out ASPECT commit ID at run time

### ISSUE THREAD

**Issue by hlokavarapu** [geodynamics/aspect#1674] opened 2017-05-15 15:16 UTC
As the code is evolving, reproducibility of computations becomes more and more difficult. @naliboff was suggesting that one method of helping users is to record the commit id of ASPECT and write out to the log file during run time. Furthermore, if possible, recording the deal.ii commit ID linked against the ASPECT binary may be just as helpful.

**Comment by bangerth** [comment] 2017-05-15 15:28
This turns out to be difficult. deal.II has this in the file `$BUILD/include/deal.II/base/revision.h`, which is generated from `$SOURCE/include/deal.II/base/revision.h.in` during the cmake run. You can probably get the same logic from there.

The problem is that after every commit, you need to re-run cmake to keep it up to date, and this cmake run can significantly increase the time it takes to compile ASPECT (in particular if the previous commit only touched a single file that now needs to be re-compiled).

**Comment by bangerth** [comment] 2017-05-25 16:15
Fixed by #1693 and follow-ups listed there.

**Closed by bangerth** 2017-05-25 16:15 UTC
