### ISSUE TITLE
Compiler warnings dangling else

### ISSUE THREAD

**Issue by anne-glerum** [geodynamics/aspect#3479] opened 2020-04-24 15:31 UTC
Hi @MFraters, I ran into some compiler warnings that might be nice to fix:

    [303/355] Building CXX object CMakeFiles/aspect.dir/contrib/world_builder/source/features./continental_plate_models/temperature/uniform.cc.o
    /Applications/ASPECT/180719/aspect/contrib/world_builder/source/features/continental_plate_models/temperature/uniform.cc:101:13: warning: add explicit braces to avoid dangling else [-Wdangling-else]
            else if ("add")
            ^
    1 warning generated.
    [309/355] Building CXX object CMakeFiles/aspect.dir/contrib/world_builder/source/features/fault_models/temperature/uniform.cc.o
    /Applications/ASPECT/180719/aspect/contrib/world_builder/source/features/fault_models/temperature/uniform.cc:104:13: warning: add explicit braces to avoid dangling else [-Wdangling-else]
            else if ("add")
            ^
    1 warning generated.
    [319/355] Building CXX object CMakeFiles/aspect.dir/contrib/world_builder/source/features/mantle_layer_models/temperature/uniform.cc.o
    /Applications/ASPECT/180719/aspect/contrib/world_builder/source/features/mantle_layer_models/temperature/uniform.cc:101:13: warning: add explicit braces to avoid dangling else [-Wdangling-else]
            else if ("add")
            ^
    1 warning generated.
    [328/355] Building CXX object CMakeFiles/aspect.dir/contrib/world_builder/source/features/oceanic_plate_models/temperature/uniform.cc.o
    /Applications/ASPECT/180719/aspect/contrib/world_builder/source/features/oceanic_plate_models/temperature/uniform.cc:101:13: warning: add explicit braces to avoid dangling else [-Wdangling-else]
            else if ("add")
            ^
    1 warning generated.
    [353/355] Building CXX object CMakeFiles/aspect.dir/contrib/world_builder/source/parameters.cc.o
    In file included from /Applications/ASPECT/180719/aspect/contrib/world_builder/source/parameters.cc:27:
    /Applications/ASPECT/180719/aspect/contrib/world_builder/include/rapidjson/latexwriter.h:140:9: warning: add explicit braces to avoid dangling else [-Wdangling-else]
        else
        ^
    1 warning generated.

My compiler: Clang 10.0.1.10010046 on platform Darwin x86_64

**Comment by tjhei** [comment] 2020-04-24 15:34
yes, I noticed those as well the other day. Those warnings are new in clang 10.

**Comment by tjhei** [comment] 2020-06-03 18:13
@MFraters can you take a look, please?

**Comment by MFraters** [comment] 2020-06-04 22:16
ah, sorry. I somehow completely missed this issue. I will see if I can reproduce and fix it.

**Comment by MFraters** [comment] 2020-06-05 06:21
It has been fixed in the master branch of the world builder. I havn't done everything I wanted for the next world builder release, but most of those things can be shifted to 0.4. So I see no problem with doing a 0.3 release just before the aspect release, so that it contains the fixes. When is the aspect release planned?

**Comment by tjhei** [comment] 2020-06-05 14:34
> So I see no problem with doing a 0.3 release just before the aspect release, so that it contains the fixes. When is the aspect release planned?

Maybe in 2 weeks? It would be good to have the updated world builder in a week or so, because we want to check compilation with various configurations.

**Comment by MFraters** [comment] 2020-06-05 16:35
Ok, I am mostly done teaching now, so I think it is feasible to me to finish a few more things in the world builder and to do a release in a week or so.

**Comment by tjhei** [comment] 2020-06-17 16:07
any update on the situation, Menno?

**Comment by MFraters** [comment] 2020-06-17 16:53
It took me a bit longer than expected, but I just merged one of the last big things I wanted to to before the release. I could make the new release now, but I would like to to one more small thing, which I hope can be done before the end of the day. So if that is fine with you, I can do the release of the world builder by the end of the day or beginning of tomorrow and make the pull request directly after that. Does that work for the aspect release?

**Comment by tjhei** [comment] 2020-06-24 12:07
we merged #3546 and I no longer see the warning.

**Closed by tjhei** 2020-06-24 12:07 UTC
