### ISSUE TITLE
sphinx online documentation

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#4595] opened 2022-05-16 15:18 UTC
Meta issue for anything related to the new documentation.

- [x] initial conversion #4593
- [x] parse version number from ~/VERSION
- [ ] move output into ASPECT build directory
- [x] setup readthedocs
- [x] update links on website, README, etc.
- [ ] make a helpful index page
- [x] run doc in CI?

**Comment by gassmoeller** [comment] 2022-05-16 20:15
We have a very early version of the documentation online here: https://aspect-doc.readthedocs.io/en/latest/user/index.html

**Comment by cmills1095** [comment] 2022-05-16 21:39
- [X] Introduction
  - [X] Referencing ASPECT
  - [X] Acknowledgements
- [ ] Geodynamic modeling assumptions and numerical methods in ASPECT
  - [X] Basic equations
    - [X] A comment on adiabatic heating
    - [X] Boundary conditions
    - [X] Two-dimensional models
    - [X] Comments on the final set of equations
  - [X] Coefficients
    - [X] Coefficient self-consistency
    - [X] Coefficient averaging
  - [X] Dimensional or non-dimensionalized equations?
    - [X] Years or seconds??
  - [X] Static or dynamic pressure?
  - [X] Pressure normalization
  - [X] Initial conditions and the adiabatic pressure/temperature
  - [X] Compositional fields
  - [X] Constitutive laws
  - [X] Numerical methods
  - [X] Approximate equations
    - [X] ALA
    - [X] TALA
    - [X] BA
    - [X] ICA
  - [X] Choosing a formulation in ASPECT
    - [X] Mass conservation approximation
    - [X] Temperature equation approximation
    - [X] Approximation of the buoyancy term
    - [X] Reference state: The adiabatic profile
    - [X] Combined formulations
  - [ ] Advection Stabilization
    - [ ] SUPG Stabilization
    - [ ] Entropy viscosity 
  - [ ] Free surface calculation
    - [ ] Arbitrary Lagrangian-Eulerian implementation
    - [ ] Free surface stabilization
  - [ ] Calculations with melt transport
  - [ ] Nullspace removal
  - [ ] Particles
  - [ ] Geometric Multigrid
- [ ] Installation
  - [ ] Docker Container
    - [ ] Installing Docker and downloading the ASPECT image 
    - [ ] Running ASPECT models
    - [ ] Developing ASPECT within a container
  - [ ] Virtual Machine
    - [ ] Installing VM software and setting up the virtual machine
    - [ ] Running ASPECT models 
  - [ ] Local installation
    - [ ] System prerequisites
    - [ ] Using candi to compile dependencies
    - [ ] Obtaining ASPECT and initial configuration
    - [ ] Compiling ASPECT and generating documentation 
- [ ] Running ASPECT
  - [ ] First steps
  - [ ] Overview
  - [ ] Selecting between 2d and 3d runs
  - [ ] Debug or optimized mode
  - [ ] Visualizing results
    - [ ] Visualization the graphical output using Visit
    - [ ] Visualizing statistical data
    - [ ] Large data issues for parallel computations
  - [ ] Checkpoint/restart support
  - [ ] Making ASPECT run faster
    - [ ] Debug vs optimized mode
    - [ ] Adjusting solver tolerances
    - [ ] Adjusting solver preconditioner tolerances
    - [ ] Using lower order elements for the temperature/compositional discretization
    - [ ] Limiting postprocessing
    - [ ] Switching off pressure normalization
    - [ ] Regularizing models with large coefficient variation
    - [ ] Using multithreading
  - [ ] Input parameter files
    - [ ] The structure of parameter files
    - [ ] Categories of parameters
    - [ ] A note on the syntax of formulas in input files
    - [ ] Compatibility of input files with newer ASPECT versions
  - [ ] A graphical user interface for editing ASPECT parameter files
    - [ ] Installing parameter-GUI
    - [ ] Using ASPECT-GUI
- [ ] Cookbooks
  - [ ] How to set up computations
  - [ ] Simple setups
    - [ ] Convection in a 2d box
    - [ ] Convection in a 3d box
    - [ ] Convection in a box with prescribed, variable velocity boundary conditions
    - [ ] Using passive and active compositional fields
    - [ ] Using particles
    - [ ] Using a free surface
    - [ ] Using a free surface in a model with a crust
    - [ ] Averaging material properties
    - [ ] Prescribed internal velocity constraints
    - [ ] Prescribing internal velocity constraints with ASCII files
    - [ ] Artificial viscosity smoohting
    - [ ] Tracking finite strain
    - [ ] Reading in compositional initial composition files generated with geomIO
    - [ ] Using lazy expression syntax for if-else-statements in function expressions
    - [ ] Convection in a 2d box with a phase transition
    - [ ] Visualizing phase diagrams
    - [ ] Plume in a 2D chunk
  - [ ] Geophysical setups
    - [ ] Simple convection in a quarter of a 2d annulus
    - [ ] Simple convection in a spherical 3d shell
    - [ ] Postprocessing spherical 3D convection
    - [ ] 3D convection with an Earth-like initial condition
    - [ ] Using reconstructed surface velocities by GPlates
    - [ ] 2D compressible convection with a reference profile and material properties from BurnMan
    - [ ] Convection using a pressure-temperature look-up table and the rheology of Steinberger and Calderwood (2006)
    - [ ] Reproducing rheology of Morency and Doin, 2004
    - [ ] Crustal deformation
    - [ ] Continental extension
    - [ ] Inner core convection
    - [ ] Melt migration in a 2D mantle convection model
    - [ ] Melt migration in a 2D mid-ocean ridge model
    - [ ] Kinematically-driven 2d oceanic subduction
  - [ ] Teaching setups
    - [ ] Running a geodynamic model
    - [ ] Convective and conductive heat flow: Cooling of oceanic lithosphere
    - [ ] Onset of convection
    - [ ] Magnetic lineations on the sea floor
- [ ] Benchmarks
  - [ ] Running benchmarks that require code
  - [ ] Onset of convection benchmark
  - [ ] The van Keken thermomechanical composition benchmark
  - [ ] Computation of the van Keken Problem with the Volume-of-Fluid Interface Tracking Method
  - [ ] The Bunge et al. mantle convection experiments
  - [ ] The Rayleigh-Taylor instability
  - [ ] Polydiapirism
  - [ ] The sinking block benchmark
  - [ ] The SolCx Stokes benchmark
  - [ ] The SolKz Stokes benchmark
  - [ ] The "inclusion" Stokes benchmark
  - [ ] The Burstedded variable viscosity benchark
  - [ ] The slab detachment benchmark
  - [ ] The hollow sphere benchmark
  - [ ] The 2D annulus benchmark
  - [ ] The "Stokes' law" benchmark
  - [ ] Latent heat benchmark
  - [ ] The 2D cylindrical shell benchmarks by Davies et al.
  - [ ] The Carmeri et al. benchmarks
  - [ ] The solitary wave benchmark
  - [ ] Benchmarks for operator splitting
  - [ ] The Tosi et al. benchmarks
  - [ ] Layered flow with viscosity contrast
  - [ ] Donea & Huerta 2D box geometry benchmark
  - [ ] Advection stabilization benchmarks
  - [ ] Yamauchi & Takei anelastic shear wave velocity-temperature conversion benchmark
  - [ ] Thin shell gravity benchmark
  - [ ] Thick shell gravity benchmark
  - [ ] Gravity field generated by mantle density variations
  - [ ] Brittle thrust wedges benchmark
- [ ] Extending and contributing to ASPECT
  - [ ] The idea of plugins and the SimulatorAccess and Introspection classes
  - [ ] How to write a plugin
  - [ ] How to write a cookbook
    - [ ] Parameter file
    - [ ] Plugins and other additional file
    - [ ] Section in the manual
  - [ ] Available plugin types
    - [ ]  Material models
    - [ ] Heating models
    - [ ] Geometry models
    - [ ] Initial conditions
    - [ ] Prescribed velocity boundary conditions
    - [ ] Temperature boundary conditions
    - [ ] Postprocessors: Evaluating the solution after each time step
    - [ ] Visualization postprocessors
    - [ ] Mesh refinement criteria
    - [ ] Criteria for terminating a simulation
  - [ ] Compatibility of plugins with newer ASPECT versions
  - [ ] Extending ASPECT through the signals mechanism
  - [ ] Extending the basic solver
  - [ ] Testing ASPECT
    - [ ]  Running tests
    - [ ] Writing tests
    - [ ] Test properties
  - [ ] Contributing to ASPECT's development
  - [ ] Future plans fo ASPECT
- [ ] Finding answers to more questions
- [ ] Run-time input parameters

**Comment by cmills1095** [comment] 2022-05-17 17:23
https://aspect-documentation.readthedocs.io/en/latest/user/index.html

**Comment by tjhei** [comment] 2022-05-17 17:30
awesome. Would it make sense to get rid of the index page and always show user/ ? I don't like that we don't have the navbar on the left on the front page.

**Comment by danieldouglas92** [comment] 2022-05-17 18:09
I'll take the prescribed_velocity cookbook!

**Comment by tjhei** [comment] 2022-05-18 15:40
How are we going to refer to ASPECT: just as "ASPECT" or using ``<span class="smallcaps">ASPECT</span>``?

**Comment by cmills1095** [comment] 2022-05-19 03:54
> How are we going to refer to ASPECT: just as "ASPECT" or using `<span class="smallcaps">ASPECT</span>`?

Do the tags actually change anything? It seemed like it didn’t so I deleted most of them, but it would be simple to use them if thats what y’all want

**Comment by cmills1095** [comment] 2022-05-19 03:57
> awesome. Would it make sense to get rid of the index page and always show user/ ? I don't like that we don't have the navbar on the left on the front page.

This (and some other issues I’ve seen brought up) are a function of the pydata theme we’re using. I’m in no way married to that theme and it should be easy to change, here’s the available themes that I’m aware of: https://sphinx-themes.org/

**Comment by bobmyhill** [comment] 2022-05-19 08:36
I don't think the index problem is due to the theme. At least, the sample at https://sphinx-themes.org/ behaves differently to the current aspect docs.

The index should normally reside at the left hand side, or in the drop down menu for smartphones. 

(Personally, I like the standard readthedocs theme, but pydata is also good.)

**Comment by alarshi** [comment] 2022-05-19 14:42
I will work on the  Artificial viscosity smoothing cookbook.

**Comment by tjhei** [comment] 2022-05-19 14:42
The one we are currently using is not great on mobile (or a narrow browser window) because the index should be in a dropdown instead of taking up the whole screen. I don't have a strong preference for a theme, but I think we might want to customize the colors a little bit (like a reddish header or sidebar or something)

**Comment by gassmoeller** [comment] 2022-05-19 14:51
Regarding the theme: I like what Menno did with the WorldBuilder documentation, should we copy that?
https://gwb.readthedocs.io/en/latest/

**Comment by bobmyhill** [comment] 2022-05-19 17:19
@tjhei, I think it's the structure of index.md that controls how the index is displayed, not the theme.
See, for example, Menno's index.md: https://raw.githubusercontent.com/GeodynamicWorldBuilder/WorldBuilder/main/doc/sphinx/index.md

Vs. the current ASPECT one:
https://raw.githubusercontent.com/geodynamics/aspect/main/doc/sphinx/user/index.md

**Comment by tjhei** [comment] 2022-05-19 17:57
> Vs. the current ASPECT one:

This is not sphinx/index.md by the way but in a subdirectory /user/.

**Comment by bobmyhill** [comment] 2022-05-19 18:03
Ah yes, sorry. Comment updated. Nevertheless, the full TOC would be in the drop down if it were specified in https://raw.githubusercontent.com/geodynamics/aspect/main/doc/sphinx/index.md

**Comment by cmills1095** [comment] 2022-05-20 00:33
It seems important to clarify what is meant by "clean up the formatting," a phrase I've been using quite liberally without explaining. Here's a list (which may be updated if I remember something else) of what I'm doing whenever I "clean up" an .md file representing a section/subsection/cookbook/benchmark:

 - Headers: Are headers properly formatted, with no duplicates? See quickref.md

 - Code blocks, figures, tables, prm files, web links, footnotes - Make sure they're properly formatted. see quickref.md for guidelines. Figures that are referenced in cookbook or benchmark documentation should be present in the same directory as the markdown file. Figures that are referenced in NON-cookbook/benchmark manual pages should be in doc/sphinx/_static/images (maybe?) and you may have to move them into that folder from wherever they currently are (probably doc/manual).

 - Math formatting - inline math formatting is usually setup correctly already. Math blocks may need review. See quickref.md for proper formatting.

 - References to equations, figures, tables, etc. - see quickref for proper formatting; note that some files reference equations in other files.

 - Citations - these were unfortunately hard-coded into the text by the auto-conversion so it can be easy to miss them. See quickref.md for how to properly format citations. You may have to dive into references.bib to find out what the proper citation code is, but ideally I would like the citation codes to be changed to be intuitive, so that we can simply use the convention 'firstauthor:year' for single author, 'firstauthor:secondauthor:year' for two, or 'firstauthor:etal:year' for more than two. However, as of now most of references.bib is 'ZPF86' and 'KMM2010' - which I change when I get the chance. There are also a lot of duplicate entries in references.bib and I delete these when I see them (though I'm careful to make absolutely sure they're duplicates, sometimes its same authors, same year, slightly different title or something like that).

 - References to other sections (NON-parameter files) - Properly format (see quickref.md). Most labels did not come over with the autoconversion; I'd like the labels to be as intuitive as possible and follow a predictable convention, which is how I've tried to set them up so far. Note that its very possible for a reference in file A to point to a file B which does not have a label, in which case you'll have to add a label to file B and include that edit as part of the pull request.

 - References to parameter files - not much we can do about these right now; if the file has some parameter references, leave it as is and add a TODO box like 
```md
:::{admonition} TODO
Parameter references
:::
```

 - General text formatting - delete stray html tags, fix any typos. Be aware that for some reason, some cookbooks/benchmarks files will just have all instances of the word ASPECT deleted and I don't know why. So keep an eye out for sentences that look like "The remainder of this section shows a number of applications of ."

 - Notes/warnings/etc - These seem to have not carried over from the autoconversion. See quickref.md for formatting and copy/paste them from the pdf manual (I recommend having the pdf manual open whenever you're editing a section anyway) or the tex file if it has a lot of math symbols.

A file which has been checked in my [above mega-checklist comment](https://github.com/geodynamics/aspect/issues/4595#issuecomment-1128164609) should have all of the above points fixed/working properly. I am currently working my way through the manual page by page to fix each of these things - though some can and has been addressed en masse with clever scripting :-) 

Manual authors, please let me know if you have comments about anything I've said here - particularly about the image locations, and the re-naming of citation tags and section tags. I'm sort of making this up as I go and taking a lot of liberties with your years of labor

**Comment by bangerth** [comment] 2022-05-20 01:38
On 5/19/22 18:33, cmills1095 wrote:
> Manual authors, please let me know if you have comments about anything I've
>  said here - particularly about the image locations, and the re-naming of 
> citation tags and section tags.

These two are conceptually the right thing to do, but they break the current 
pdf manual. We should only do that if we decide that we're not going to build 
the pdf manual any more every night.

**Comment by cmills1095** [comment] 2022-05-20 01:42
> On 5/19/22 18:33, cmills1095 wrote: Manual authors, please let me know if you have comments about anything I've said here - particularly about the image locations, and the re-naming of citation tags and section tags.
> These two are conceptually the right thing to do, but they break the current pdf manual. We should only do that if we decide that we're not going to build the pdf manual any more every night.

The references.bib file I'm editing is in doc/sphinx and separate from the one the pdf manual references. And when I said moving images, I really meant copying them, for now. Though we could just as easily leave the images in their current folder and reference them like ../../../../manual/image.pdf . This shouldn't affect the pdf manual, right?

**Comment by bangerth** [comment] 2022-05-20 15:43
Editing a copy is fine. For both the bib file and the pictures, creating copies is conceptually problematic, but I think we intend to get rid of the originals at some point, so that's ok with me.

**Comment by cmills1095** [comment] 2022-05-20 18:14
Issue: Sphinx doesn't support sub-figures, and forums seem to indicate they have no intention of changing that. There is an easy way to make subfigures work by putting them in a list-tables; it looks good, but its not a figure and so won't be numbered as a figure and can't be referenced by a figure number, so probably not acceptable for our purposes. The alternative is to consolidate figures in inkscape, which is tedious but I've done one to make sure it works and its not too difficult. My question is: is there any reason we'd want to leave two subfigures as separate png files? Or can I consolidate and then delete the originals?

**Comment by bangerth** [comment] 2022-05-20 20:10
If you ever want to re-use parts of the figure, it's super tedious to get them back out. Can a figure be only a single image file? It can't be anything else than a single file?

**Comment by cmills1095** [comment] 2022-05-21 14:39
> If you ever want to re-use parts of the figure, it's super tedious to get them back out. Can a figure be only a single image file? It can't be anything else than a single file?

That seems to be the case, unfortunately

**Comment by Wang-yijun** [comment] 2022-05-22 22:39
I'm working on the  "Convection in a 3d box" and "Convection in a box with prescribed, variable velocity boundary conditions" cookbooks.

**Comment by bangerth** [comment] 2023-07-13 22:38
What's left here?

**Comment by gassmoeller** [comment] 2024-10-07 12:55
I think the only remaining point is that it would be nice to have the build directory of the sphinx documentation be in the general build directory. In essence to extend doc/CMakeLists.txt to actually build the documentation instead of just preparing the images. But overall these are nice-to-have features, which I think should be tracked in a separate issue. The main point of this issue is the conversion to the sphinx documentation which is finished.

**Closed by gassmoeller** 2024-10-07 12:55 UTC
